### ISSUE TITLE
Typescript autocomplete is not working 

### ISSUE THREAD

**Issue by noskovvkirill** [tamagui/starters#3]
Hi! I was trying this starter template, but can't get IntelliSense working. Haven't changed anything in the source code. Restarted typescript server to make sure it's working. 😕  Any ideas why that might be the case? 

**In this example, it shows me the default CSS colors:** 
<img width="500" alt="Снимок экрана 2022-06-06 в 23 33 49" src="https://user-images.githubusercontent.com/50060130/172253251-1899b37f-e001-4fca-889a-c31d9470c97d.png">

The same happens if I try to use Tamagui components directly. It accepts the correct types, but no luck with autocomplete.

**Comment by natew** [comment]
Join the discord, but also try the latest there's been many releases.
