### ISSUE TITLE
[Bug][Native] User Detail Screen Link To Home Fails

### ISSUE THREAD

**Issue by Afulton11** [tamagui/starters#4]
Hi,

The `< Go Home` button fails to navigate to the homepage on native (I only tested on iOS). This could be a problem specific to *solito*.

### Reproduction
1. Clone the `next-expo-solito` starter
2. Run `yarn native`
3. Open the app in iOS
4. Tap `Link to user`
5. Attempt to go back Home using the `< Go Home` button

### Possible Solution
Follow the same pattern used in the HomeScreen to create a link (using the `useLink` Hook):
```jsx
export function UserDetailScreen() {
  const [id] = useParam('id')
  const homeLinkProps = useLink({
    href: '/',
  })

  return (
    <YStack f={1} jc="center" ai="center" space>
      <Paragraph ta="center" fow="800">{`User ID: ${id}`}</Paragraph>
      <Button {...homeLinkProps} icon={ChevronLeft}>
        Go Home
      </Button>
    </YStack>
  )
}
```

**Comment by hirbod** [comment]
I can confirm this

**Comment by natew** [comment]
Fixed, we have to use `useLink` because of a RN bug with Pressable in Pressable.
